### ISSUE TITLE
How to inference on 1544*896 images

### ISSUE THREAD

**Issue by jiangyitong** [Yuliang-Liu/Monkey#158]
Hi, in the paper there are results of 1544*896 images. May I ask how I can use inference.py to inference 1544*896 images or larger?

**Comment by echo840** [comment]
Thank you for your interest in our work. Currently, the released model is trained at a resolution of 896×896. Since the required number of LoRA differs for a resolution of 1344×896, it may not be possible to directly modify the resolution of the released model to 1344×896. However, if you wish to train a model at the 1344×896 resolution, you can refer to the TextMonkey training code below for the necessary modifications, or you may use the TextMonkey model architecture directly for training.

In the image below:
1. The code in box labeled "1" shows where to set the input image size.
2. The code in box labeled "2" indicates where to specify the number of LoRA. For a 1344×896 resolution, the number of LoRA parameters is calculated as (1344/448) × (896/448) = 6.
3. The code in box labeled "3" is used to set the number of pre-filled image tokens when encoding the input query with the tokenizer.

![image](https://github.com/user-attachments/assets/60eb0db5-4334-453e-ba3b-7541f90c37c2)
